import { Knex } from "knex";
import { ETableNames } from "../ETableNames";



export const seed = async (knex: Knex) => {
    const [{count}] = await knex(ETableNames.cidade).count<[{count: number}]>('* as count');
    if (!Number.isInteger(count)||Number(count)>0) return;

    const cidadesToInsert = cidadesDoParana.map(nomeDaCidade => ({nome: nomeDaCidade}));
    await knex(ETableNames.cidade).insert(cidadesToInsert);

};

const cidadesDoParana = [

    "Curitiba", 
    "Londrina", 
    "Maringá", 
    "Ponta Grossa", 
    "Cascavel", 
    "São José dos Pinhais", 
    "Foz do Iguaçu", 
    "Colombo", 
    "Guarapuava", 
    "Araucária", 
    "Fazenda Rio Grande", 
    "Toledo", 
    "Paranaguá", 
    "Campo Largo", 
    "Apucarana", 
    "Pinhais", 
    "Almirante Tamandaré", 
    "Arapongas", 
    "Piraquara", 
    "Sarandi", 
    "Umuarama", 
    "Cambé", 
    "Campo Mourão", 
    "Francisco Beltrão", 
    "Paranavaí", 
    "Pato Branco", 
    "Cianorte", 
    "Telêmaco Borba", 
    "Castro", 
    "Rolândia", 
    "Irati", 
    "União da Vitória", 
    "Marechal Cândido Rondon", 
    "Ibiporã", 
    "Prudentópolis", 
    "Palmas", 
    "Campina Grande do Sul", 
    "Medianeira", 
    "Santo Antônio da Platina", 
    "Paiçandu", 
    "Cornélio Procópio", 
    "Lapa", 
    "Dois Vizinhos", 
    "São Mateus do Sul", 
    "Guaratuba", 
    "Jacarezinho", 
    "Marialva", 
    "Matinhos", 
    "Rio Branco do Sul", 
    "Assis Chateaubriand", 
    "Mandaguari", 
    "Jaguariaíva", 
    "Palotina", 
    "Palmeira", 
    "Pitanga", 
    "Ivaiporã", 
    "Laranjeiras do Sul", 
    "Guaíra", 
    "Mandaguaçu", 
    "Rio Negro", 
    "Bandeirantes", 
    "Itaperuçu", 
    "Quedas do Iguaçu", 
    "Pontal do Paraná", 
    "Imbituva", 
    "Campo Magro", 
    "Pinhão", 
    "São Miguel do Iguaçu", 
    "Ibaiti", 
    "Goioerê", 
    "Mandirituba", 
    "Nova Esperança", 
    "Arapoti", 
    "Santa Helena", 
    "Astorga", 
    "Ubiratã", 
    "Reserva", 
    "Santa Terezinha de Itaipu", 
    "Ortigueira", 
    "Quatro Barras", 
    "Cruzeiro do Oeste", 
    "Santo Antônio do Sudoeste", 
    "Piraí do Sul", 
    "Coronel Vivida", 
    "Carambeí", 
    "Loanda", 
    "Cambará", 
    "Colorado", 
    "Siqueira Campos", 
    "Jandaia do Sul", 
    "Chopinzinho", 
    "Capanema", 
    "Tibagi", 
    "Andirá", 
    "Ampére", 
    "Realeza", 
    "Wenceslau Braz", 
    "Contenda", 
    "Cafelândia", 
    "Altônia", 
    "Matelândia", 
    "Quitandinha", 
    "Morretes", 
    "Terra Roxa", 
    "Antonina", 
    "Tijucas do Sul", 
    "Terra Boa", 
    "Corbélia", 
    "Sengés", 
    "Mangueirinha", 
    "Faxinal", 
    "Cerro Azul", 
    "Cruz Machado", 
    "Sertanópolis", 
    "Marmeleiro", 
    "Tapejara", 
    "Bituruna", 
    "Cândido de Abreu", 
    "Salto do Lontra", 
    "Clevelândia", 
    "Candói", 
    "Terra Rica", 
    "Bela Vista do Paraíso", 
    "Capitão Leônidas Marques", 
    "Rebouças", 
    "Ipiranga", 
    "Santa Izabel do Oeste", 
    "Rio Azul", 
    "Alto Paraná", 
    "Assaí", 
    "São João do Triunfo", 
    "Curiúva", 
    "Tamarana", 
    "Carlópolis", 
    "Paraíso do Norte", 
    "Ivaí", 
    "Araruna", 
    "Peabirú", 
    "Engenheiro Beltrão", 
    "Campina da Lagoa", 
    "Jaguapitã", 
    "Mallet", 
    "General Carneiro", 
    "Iporã", 
    "Manoel Ribas", 
    "Imbaú", 
    "Planalto", 
    "Cantagalo", 
    "Bocaiuva do Sul", 
    "Rio Bonito do Iguaçu", 
    "Balsa Nova", 
    "Nova Londrina", 
    "Piên", 
    "Turvo", 
    "Cidade Gaúcha", 
    "Mamborê", 
    "Ribeirão do Pinhal", 
    "Teixeira Soares", 
    "Palmital", 
    "Jataizinho", 
    "Porecatu", 
    "Querência do Norte", 
    "Guaraniaçu", 
    "Santa Fé", 
    "Itapejara d'Oeste", 
    "Ventania", 
    "Moreira Sales", 
    "Três Barras do Paraná", 
    "Joaquim Távora", 
    "Céu Azul", 
    "Santa Mariana", 
    "Paranacity", 
    "Nova Laranjeiras", 
    "Alvorada do Sul", 
    "Barbosa Ferraz", 
    "Itaipulândia", 
    "Pérola", 
    "Uraí", 
    "Jardim Alegre", 
    "Primeiro de Maio", 
    "São Jerônimo da Serra", 
    "Inácio Martins", 
    "São Pedro do Ivaí", 
    "Mauá da Serra", 
    "Centenário do Sul", 
    "Missal", 
    "Ribeirão Claro", 
    "Nova Prata do Iguaçu", 
    "Florestópolis", 
    "Mariluz", 
    "Barracão", 
    "Nova Aurora", 
    "São João", 
    "Catanduvas", 
    "Iretama", 
    "Santa Tereza do Oeste", 
    "São João do Ivaí", 
    "Alto Piquiri", 
    "Roncador", 
    "Rondon", 
    "Japurá", 
    "Agudos do Sul", 
    "Santa Maria do Oeste", 
    "São Jorge d'Oeste", 
    "Tunas do Paraná", 
    "Douradina", 
    "São Sebastião da Amoreira", 
    "Congonhinhas", 
    "Marilândia do Sul", 
    "Guamiranga", 
    "Califórnia", 
    "Tuneiras do Oeste", 
    "Santa Isabel do Ivaí", 
    "Vera Cruz do Oeste", 
    "Jesuítas", 
    "Nova Santa Rosa", 
    "Ivaté", 
    "Nova Fátima", 
    "Tupãssi", 
    "Reserva do Iguaçu", 
    "Campo do Tenente", 
    "Cambira", 
    "Tomazina", 
    "Icaraíma", 
    "Santa Cruz de Monte Castelo", 
    "Figueira", 
    "Guaraqueçaba", 
    "Boa Vista da Aparecida", 
    "Coronel Domingos Soares", 
    "Quatiguá", 
    "Antônio Olinto", 
    "Abatiá", 
    "Paulo Frontin", 
    "Juranda", 
    "Luiziana", 
    "Bom Sucesso", 
    "Verê", 
    "Marilena", 
    "Goioxim", 
    "Jussara", 
    "São Carlos do Ivaí", 
    "Sabáudia", 
    "Vitorino", 
    "Floresta", 
    "Renascença", 
    "Sapopema", 
    "Mariópolis", 
    "Guairaçá", 
    "Itambaracá", 
    "Amaporã", 
    "Ibema", 
    "Formosa do Oeste", 
    "Boa Ventura de São Roque", 
    "Pinhalão", 
    "Borrazópolis", 
    "Pérola d'Oeste", 
    "Perobal", 
    "São José da Boa Vista", 
    "Itambé", 
    "Ouro Verde do Oeste", 
    "Doutor Camargo", 
    "Francisco Alves", 
    "Paula Freitas", 
    "Enéas Marques", 
    "Nova Olímpia", 
    "São João do Caiuá", 
    "Adrianópolis", 
    "São Tomé", 
    "Pato Bragado", 
    "São Pedro do Iguaçu", 
    "Laranjal", 
    "Mercedes", 
    "Maria Helena", 
    "Xambrê", 
    "Saudade do Iguaçu", 
    "Maripá", 
    "Fernandes Pinheiro", 
    "Guaraci", 
    "São Jorge do Ivaí", 
    "São Jorge do Patrocínio", 
    "Doutor Ulysses", 
    "Tapira", 
    "Santo Inácio", 
    "Presidente Castelo Branco", 
    "Grandes Rios", 
    "Braganey", 
    "Jaboti", 
    "Diamante D'Oeste", 
    "Nova Tebas", 
    "Tamboara", 
    "Sertaneja", 
    "Pranchita", 
    "Honório Serpa", 
    "Nova Esperança do Sudoeste", 
    "Diamante do Norte", 
    "Lupionópolis", 
    "Janiópolis", 
    "Japira", 
    "Santana do Itararé", 
    "Porto Amazonas", 
    "Floraí", 
    "Salto do Itararé", 
    "Lobato", 
    "Nova Cantu", 
    "Fênix", 
    "Lunardelli", 
    "Marumbi", 
    "Entre Rios do Oeste", 
    "Rosário do Ivaí", 
    "Flor da Serra do Sul", 
    "Ramilândia", 
    "Lindoeste", 
    "Iguaraçu", 
    "Indianópolis", 
    "Foz do Jordão", 
    "Serranópolis do Iguaçu", 
    "Quinta do Sol", 
    "Cruzeiro do Sul", 
    "Itaguajé", 
    "Quarto Centenário", 
    "Nova Santa Bárbara", 
    "Marquinho", 
    "Planaltina do Paraná", 
    "Cruzeiro do Iguaçu", 
    "Rio Branco do Ivaí", 
    "Porto Vitória", 
    "Santa Mônica", 
    "Virmond", 
    "Quatro Pontes", 
    "Munhoz de Melo", 
    "Nossa Senhora das Graças", 
    "Kaloré", 
    "Boa Esperança", 
    "Espigão Alto do Iguaçu", 
    "Cafezal do Sul", 
    "Leópolis", 
    "Conselheiro Mairinck", 
    "Atalaia", 
    "Campina do Simão", 
    "Prado Ferreira", 
    "Santa Lúcia", 
    "Guapirama", 
    "Rancho Alegre", 
    "Campo Bonito", 
    "São José das Palmeiras", 
    "Bom Jesus do Sul", 
    "Nova América da Colina", 
    "Ourizona", 
    "Diamante do Sul", 
    "Bela Vista da Caroba", 
    "Salgado Filho", 
    "Ivatuba", 
    "Pitangueiras", 
    "Paranapoema", 
    "Santa Cecília do Pavão", 
    "Jundiaí do Sul", 
    "Bom Sucesso do Sul", 
    "Santa Amélia", 
    "Rio Bom", 
    "Lidianópolis", 
    "Mato Rico", 
    "Porto Barreiro", 
    "Inajá", 
    "Corumbataí do Sul", 
    "Farol", 
    "Cafeara", 
    "Arapuã", 
    "Ângulo", 
    "Cruzmaltina", 
    "Sulina", 
    "Godoy Moreira", 
    "Novo Itacolomi", 
    "Barra do Jacaré", 
    "Anahy", 
    "Pinhal de São Bento", 
    "Flórida", 
    "Itaúna do Sul", 
    "Alto Paraíso", 
    "Uniflor", 
    "Santo Antônio do Caiuá", 
    "Rancho Alegre D'Oeste", 
    "Porto Rico", 
    "Brasilândia do Sul", 
    "Manfrinópolis", 
    "Boa Esperança do Iguaçu", 
    "São Pedro do Paraná", 
    "Iguatu", 
    "Guaporema", 
    "Iracema do Oeste", 
    "Mirador", 
    "São Manoel do Paraná", 
    "Santo Antônio do Paraíso", 
    "Ariranha do Ivaí", 
    "Miraselva", 
    "Esperança Nova", 
    "Santa Inês", 
    "Altamira do Paraná", 
    "Jardim Olinda", 
    "Nova Aliança do Ivaí"
];
